In [21]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

os.chdir('/home/melissa/PROJECT_DIRECTORIES/EEGFeatureExtraction/Scripts/Preprocessing/')
%run constants.py

In [40]:
def remove_na_df(df):
    processed_columns = []
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    #drop na values in each column
    for column in df.columns:
        processed_column = df[column].dropna().reset_index(drop=True)
        processed_columns.append(processed_column)

    result_df = pd.concat(processed_columns, axis=1)
    result_df = result_df.dropna()
    result_df.columns = [f"{col}_cc" if col not in ['Epoch', 'Animal_ID'] else col for col in df.columns]

    
    return result_df

In [41]:
results_path = '/home/melissa/PROJECT_DIRECTORIES/EEGFeatureExtraction/Results/Connectivity/'
all_animals = []
for animal in SYNGAP_1_ls:
    print(animal)
    df = pd.read_csv(results_path + f'{animal}_cross_corr.csv')
    result_df = remove_na_df(df)
    all_animals.append(result_df)

S7076
S7101
S7088
S7092
S7094
S7098
S7068
S7074
S7076
S7071
S7075

In [42]:
all_animals_concat = pd.concat(all_animals)

In [43]:
all_animals_concat

,Epoch,Animal_ID,0_2_delta_cc,0_3_delta_cc,0_4_delta_cc,0_5_delta_cc,0_6_delta_cc,0_7_delta_cc,0_8_delta_cc,0_9_delta_cc,...,10_11_gamma_cc,10_12_gamma_cc,10_13_gamma_cc,10_15_gamma_cc,11_12_gamma_cc,11_13_gamma_cc,11_15_gamma_cc,12_13_gamma_cc,12_15_gamma_cc,13_15_gamma_cc
0,0,S7076,0.461879,0.664243,0.609397,0.722496,0.678915,0.756599,0.590976,0.545495,...,0.959293,0.956347,0.832111,0.963411,0.962864,0.909954,0.904592,0.917952,0.916966,0.789241
1,1,S7076,0.492624,0.803205,0.780439,0.848030,0.550736,0.733486,0.783964,0.653109,...,0.962405,0.967171,0.860727,0.959929,0.967912,0.913068,0.900649,0.927166,0.924946,0.800971
2,2,S7076,0.352703,0.633640,0.613290,0.775780,0.520753,0.726525,0.695055,0.484713,...,0.950481,0.961616,0.844206,0.950220,0.965284,0.908448,0.886479,0.920126,0.910530,0.786919
3,3,S7076,0.289614,0.538730,0.518668,0.570677,0.338995,0.625546,0.568553,0.410421,...,0.962381,0.971030,0.886777,0.967397,0.970528,0.933097,0.920285,0.936397,0.945508,0.865915
4,4,S7076,0.283445,0.580086,0.547229,0.782649,0.237778,0.714630,0.721157,0.607662,...,0.949363,0.965636,0.863627,0.959726,0.961616,0.928086,0.905895,0.917416,0.922833,0.824476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17275,17275,S7075,0.620075,0.844938,0.873833,0.947031,0.887903,0.931668,0.839925,0.926926,...,0.943929,0.961663,0.855583,0.932385,0.945417,0.911497,0.834677,0.898515,0.888990,0.726240
17276,17276,S7075,0.567652,0.589475,0.794845,0.879411,0.731347,0.783719,0.439369,0.736598,...,0.962005,0.964499,0.880682,0.957664,0.967597,0.930092,0.898830,0.936370,0.905310,0.788128
17277,17277,S7075,0.841146,0.921238,0.933721,0.958788,0.926685,0.951068,0.890482,0.942000,...,0.956026,0.963022,0.848064,0.947395,0.960067,0.907936,0.869897,0.908961,0.904300,0.733921
17278,17278,S7075,0.999200,0.999201,0.999201,0.999201,0.999201,0.999201,0.999201,0.999201,...,0.999200,0.999201,0.999199,0.999200,0.999200,0.999200,0.999198,0.999200,0.999199,0.999197
17279,17279,S7075,0.999183,0.999188,0.999194,0.999199,0.999194,0.999194,0.999189,0.999197,...,0.999188,0.999188,0.999169,0.999187,0.999186,0.999183,0.999170,0.999176,0.999173,0.999150

In [31]:
np.unique(all_animals_concat['Animal_ID'])

array(['S7068', 'S7071', 'S7074', 'S7075', 'S7076', 'S7088', 'S7092',
       'S7094', 'S7098', 'S7101'], dtype=object)

In [15]:
processed_columns = []

# Loop through each column, drop NA values, and append to the list
for column in test_connect.columns:
    processed_column = test_connect[column].dropna().reset_index(drop=True)
    processed_columns.append(processed_column)

# Concatenate the list of Series into a new DataFrame
result_df = pd.concat(processed_columns, axis=1)

In [19]:
result_df = result_df.dropna()